name 'chef-mysql_jboss'
maintainer 'Dmitryj'
maintainer_email 'gudrumms@gmail.com'
license 'all_rights'
description 'Installs/Configures chef-mysql_jboss'
long_description 'Installs/Configures chef-mysql_jboss'
version '0.1.0'
depends 'apt', '~> 2.9.2'
